language: node_js
node_js:
  - 6.0.0
  - 8
  - stable
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - "yarn test:ci"
